name: OAK
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - setuptools
  - numpy=1.24.3
  - scipy=1.11.4
  - hypothesis=6.150.2
  - pytest=7.4.3
  - pip:
      - depthai==2.30.0.0
      - python-can==4.2.2
      - pytest-asyncio==0.21.1
      - pytest-mock==3.12.0
      - pyyaml==6.0.1
      - ruamel-yaml==0.19.1
      - black==23.11.0
      - flake8==6.1.0
      - mypy==1.7.1
